-- Auto-generated ComputerCraft image renderer
local mon = peripheral.find('monitor') or term
mon.setTextScale(0.5)
mon.clear()

local colorMap = {
  ["white"] = 1,
  ["orange"] = 2,
  ["magenta"] = 4,
  ["lightBlue"] = 8,
  ["yellow"] = 16,
  ["lime"] = 32,
  ["pink"] = 64,
  ["gray"] = 128,
  ["lightGray"] = 256,
  ["cyan"] = 512,
  ["purple"] = 1024,
  ["blue"] = 2048,
  ["brown"] = 4096,
  ["green"] = 8192,
  ["red"] = 16384,
  ["black"] = 32768,
}

local pixels = {
  {{"gray",23}, {"brown",11}, {"lightGray",94}},
  {{"gray",25}, {"brown",12}, {"lightGray",91}},
  {{"gray",24}, {"brown",12}, {"lightGray",92}},
  {{"gray",24}, {"brown",12}, {"lightGray",92}},
  {{"gray",22}, {"brown",13}, {"lightGray",39}, {"pink",1}, {"lightGray",2}, {"pink",6}, {"lightGray",1}, {"pink",1}, {"lightGray",43}},
  {{"gray",22}, {"brown",13}, {"lightGray",40}, {"pink",10}, {"lightGray",43}},
  {{"gray",22}, {"brown",13}, {"lightGray",38}, {"brown",2}, {"lightGray",53}},
  {{"gray",22}, {"brown",13}, {"lightGray",32}, {"brown",1}, {"gray",4}, {"brown",3}, {"lightGray",53}},
  {{"gray",24}, {"brown",12}, {"lightGray",31}, {"brown",1}, {"gray",3}, {"brown",4}, {"lightGray",3}, {"pink",8}, {"lightGray",17}, {"pink",25}},
  {{"gray",24}, {"brown",13}, {"lightGray",28}, {"brown",1}, {"gray",2}, {"brown",5}, {"lightGray",2}, {"brown",2}, {"lightGray",3}, {"pink",5}, {"lightGray",9}, {"pink",34}},
  {{"gray",25}, {"brown",12}, {"lightGray",24}, {"gray",9}, {"brown",1}, {"lightGray",2}, {"lightBlue",2}, {"pink",2}, {"lightGray",7}, {"pink",2}, {"lightGray",4}, {"pink",38}},
  {{"gray",25}, {"brown",13}, {"lightGray",23}, {"gray",12}, {"lightBlue",1}, {"white",4}, {"pink",50}},
  {{"gray",26}, {"brown",12}, {"lightGray",22}, {"brown",1}, {"gray",9}, {"black",2}, {"gray",1}, {"lightBlue",1}, {"white",4}, {"pink",4}, {"white",1}, {"pink",45}},
  {{"gray",26}, {"brown",12}, {"lightGray",22}, {"gray",8}, {"brown",1}, {"lightGray",3}, {"lightBlue",1}, {"pink",2}, {"white",1}, {"pink",6}, {"white",1}, {"pink",45}},
  {{"gray",27}, {"brown",11}, {"lightGray",22}, {"gray",7}, {"brown",2}, {"lightGray",5}, {"pink",7}, {"white",1}, {"pink",46}},
  {{"gray",27}, {"brown",11}, {"lightGray",22}, {"gray",6}, {"brown",2}, {"lightGray",6}, {"pink",7}, {"white",2}, {"pink",45}},
  {{"gray",27}, {"brown",11}, {"lightGray",20}, {"pink",1}, {"lightGray",1}, {"gray",6}, {"brown",2}, {"lightGray",5}, {"pink",7}, {"white",1}, {"pink",1}, {"lightGray",1}, {"brown",1}, {"lightGray",3}, {"lightBlue",1}, {"pink",1}, {"white",4}, {"pink",35}},
  {{"gray",26}, {"brown",11}, {"lightGray",21}, {"pink",1}, {"brown",1}, {"gray",5}, {"brown",2}, {"lightGray",6}, {"pink",8}, {"gray",2}, {"lightGray",3}, {"lightBlue",1}, {"white",6}, {"lightBlue",1}, {"pink",34}},
  {{"gray",27}, {"brown",10}, {"lightGray",22}, {"gray",6}, {"brown",2}, {"lightGray",5}, {"pink",8}, {"lightGray",1}, {"gray",1}, {"brown",1}, {"lightGray",3}, {"lightBlue",1}, {"white",5}, {"cyan",1}, {"lightGray",1}, {"pink",34}},
  {{"gray",27}, {"brown",10}, {"lightGray",20}, {"pink",1}, {"lightGray",1}, {"gray",6}, {"brown",1}, {"lightGray",8}, {"pink",7}, {"lightGray",2}, {"pink",1}, {"lightGray",3}, {"pink",1}, {"white",4}, {"lightBlue",1}, {"pink",35}},
  {{"gray",27}, {"brown",10}, {"lightGray",21}, {"brown",1}, {"gray",5}, {"brown",2}, {"lightGray",7}, {"pink",55}},
  {{"gray",27}, {"brown",10}, {"lightGray",20}, {"pink",1}, {"brown",1}, {"gray",5}, {"brown",4}, {"lightGray",4}, {"pink",6}, {"yellow",2}, {"pink",48}},
  {{"brown",1}, {"gray",27}, {"brown",9}, {"lightGray",19}, {"pink",1}, {"lightGray",1}, {"gray",5}, {"brown",3}, {"lightGray",4}, {"pink",32}, {"white",2}, {"pink",1}, {"white",11}, {"pink",1}, {"white",1}, {"pink",10}},
  {{"brown",1}, {"gray",28}, {"brown",9}, {"lightGray",17}, {"pink",2}, {"lightGray",1}, {"gray",5}, {"brown",2}, {"lightGray",5}, {"pink",27}, {"white",29}, {"pink",2}},
  {{"brown",1}, {"gray",29}, {"brown",8}, {"lightGray",16}, {"pink",1}, {"lightGray",1}, {"brown",1}, {"gray",3}, {"brown",5}, {"lightGray",5}, {"pink",6}, {"yellow",1}, {"pink",16}, {"white",35}},
  {{"brown",2}, {"gray",30}, {"brown",7}, {"lightGray",17}, {"gray",4}, {"brown",2}, {"lightGray",6}, {"pink",8}, {"yellow",1}, {"pink",2}, {"white",1}, {"pink",2}, {"white",3}, {"pink",4}, {"white",39}},
  {{"brown",2}, {"gray",31}, {"brown",7}, {"lightGray",8}, {"brown",1}, {"gray",1}, {"brown",4}, {"lightGray",3}, {"brown",3}, {"gray",1}, {"brown",6}, {"lightGray",4}, {"pink",15}, {"white",42}},
  {{"gray",33}, {"brown",9}, {"lightGray",4}, {"brown",1}, {"gray",1}, {"black",1}, {"gray",1}, {"brown",3}, {"lightGray",6}, {"yellow",1}, {"lightGray",6}, {"brown",4}, {"lightGray",3}, {"brown",3}, {"lightGray",10}, {"pink",2}, {"white",40}},
  {{"gray",35}, {"brown",8}, {"lightGray",1}, {"brown",1}, {"gray",1}, {"black",2}, {"gray",1}, {"brown",3}, {"lightGray",28}, {"yellow",2}, {"lightGray",2}, {"yellow",4}, {"pink",2}, {"white",38}},
  {{"gray",37}, {"brown",7}, {"gray",1}, {"black",3}, {"gray",1}, {"brown",3}, {"lightGray",6}, {"brown",3}, {"lightGray",11}, {"yellow",1}, {"pink",1}, {"lightGray",4}, {"pink",6}, {"yellow",2}, {"pink",5}, {"white",37}},
  {{"gray",40}, {"brown",3}, {"gray",1}, {"black",4}, {"gray",1}, {"brown",3}, {"lightGray",5}, {"brown",1}, {"gray",1}, {"brown",2}, {"lightGray",5}, {"pink",9}, {"lightGray",1}, {"brown",1}, {"lightGray",1}, {"pink",7}, {"lightGray",1}, {"pink",6}, {"white",36}},
  {{"gray",42}, {"brown",1}, {"gray",1}, {"black",2}, {"gray",2}, {"brown",6}, {"lightGray",3}, {"brown",1}, {"gray",2}, {"brown",3}, {"lightGray",4}, {"pink",9}, {"lightGray",3}, {"pink",7}, {"lightGray",1}, {"pink",3}, {"yellow",1}, {"pink",2}, {"white",35}},
  {{"gray",43}, {"black",2}, {"gray",2}, {"brown",7}, {"lightGray",4}, {"gray",4}, {"brown",5}, {"lightGray",1}, {"pink",9}, {"lightGray",1}, {"red",1}, {"lightGray",1}, {"pink",4}, {"lightGray",1}, {"red",1}, {"lightGray",2}, {"pink",3}, {"yellow",2}, {"pink",2}, {"white",33}},
  {{"gray",43}, {"black",2}, {"gray",1}, {"brown",7}, {"lightGray",5}, {"brown",9}, {"lightGray",5}, {"pink",7}, {"lightGray",4}, {"brown",1}, {"gray",1}, {"brown",1}, {"red",1}, {"lightGray",2}, {"pink",3}, {"yellow",3}, {"pink",1}, {"white",32}},
  {{"gray",42}, {"black",3}, {"gray",3}, {"brown",3}, {"lightGray",1}, {"brown",1}, {"lightGray",5}, {"brown",9}, {"lightGray",6}, {"pink",8}, {"yellow",1}, {"brown",2}, {"pink",1}, {"lightGray",1}, {"brown",2}, {"red",1}, {"lightGray",3}, {"yellow",1}, {"pink",2}, {"yellow",1}, {"pink",1}, {"white",31}},
  {{"gray",42}, {"black",2}, {"gray",4}, {"brown",2}, {"lightGray",2}, {"brown",5}, {"lightGray",1}, {"brown",6}, {"lightGray",9}, {"pink",8}, {"yellow",1}, {"lightGray",1}, {"white",3}, {"lightGray",1}, {"brown",3}, {"red",1}, {"lightGray",2}, {"yellow",3}, {"pink",2}, {"white",30}},
  {{"gray",42}, {"black",2}, {"gray",1}, {"black",2}, {"gray",1}, {"brown",6}, {"gray",3}, {"brown",2}, {"gray",1}, {"brown",5}, {"lightGray",4}, {"brown",1}, {"lightGray",3}, {"pink",4}, {"yellow",1}, {"pink",2}, {"yellow",1}, {"lightGray",1}, {"pink",3}, {"lightGray",5}, {"yellow",7}, {"pink",1}, {"white",30}},
  {{"gray",42}, {"black",7}, {"gray",2}, {"brown",8}, {"gray",2}, {"brown",7}, {"lightGray",2}, {"brown",1}, {"lightGray",6}, {"pink",6}, {"lightGray",2}, {"yellow",2}, {"pink",4}, {"yellow",2}, {"pink",1}, {"yellow",4}, {"pink",1}, {"white",29}},
  {{"gray",43}, {"black",9}, {"gray",2}, {"brown",4}, {"lightGray",3}, {"brown",9}, {"lightGray",5}, {"lightBlue",2}, {"white",5}, {"pink",1}, {"lightGray",3}, {"yellow",1}, {"lightGray",10}, {"pink",1}, {"white",30}},
  {{"gray",44}, {"black",11}, {"gray",3}, {"brown",4}, {"lightGray",1}, {"brown",3}, {"gray",1}, {"brown",2}, {"gray",1}, {"lightGray",2}, {"brown",1}, {"lightGray",3}, {"lightBlue",1}, {"lightGray",1}, {"lightBlue",1}, {"white",2}, {"pink",9}, {"lightGray",2}, {"pink",4}, {"white",32}},
  {{"gray",52}, {"black",8}, {"gray",4}, {"black",3}, {"gray",1}, {"lightGray",1}, {"brown",1}, {"gray",4}, {"brown",2}, {"gray",2}, {"lightGray",1}, {"pink",1}, {"lightGray",2}, {"lightBlue",1}, {"white",1}, {"lightBlue",3}, {"white",41}},
  {{"gray",46}, {"brown",14}, {"gray",1}, {"black",6}, {"gray",11}, {"lightGray",2}, {"brown",2}, {"lightGray",4}, {"pink",10}, {"white",28}, {"pink",4}},
  {{"gray",45}, {"brown",8}, {"lightGray",5}, {"brown",2}, {"gray",11}, {"brown",3}, {"lightGray",6}, {"pink",2}, {"lightGray",3}, {"pink",1}, {"white",4}, {"pink",12}, {"white",14}, {"pink",2}, {"white",1}, {"pink",9}},
  {{"gray",44}, {"brown",9}, {"lightGray",3}, {"gray",8}, {"brown",1}, {"lightGray",12}, {"pink",2}, {"white",14}, {"pink",35}},
  {{"gray",46}, {"brown",7}, {"lightGray",3}, {"gray",8}, {"brown",3}, {"lightGray",4}, {"pink",8}, {"white",15}, {"pink",34}},
  {{"gray",47}, {"brown",8}, {"lightGray",1}, {"black",9}, {"gray",2}, {"lightGray",5}, {"pink",3}, {"white",1}, {"pink",4}, {"white",1}, {"pink",4}, {"white",9}, {"pink",34}},
  {{"gray",50}, {"brown",5}, {"gray",1}, {"black",10}, {"gray",4}, {"brown",2}, {"lightGray",2}, {"brown",2}, {"lightGray",5}, {"pink",5}, {"white",6}, {"pink",36}},
  {{"gray",53}, {"brown",2}, {"black",17}, {"gray",1}, {"black",5}, {"gray",7}, {"lightGray",5}, {"pink",38}},
  {{"gray",55}, {"black",30}, {"gray",5}, {"lightGray",1}, {"pink",37}},
  {{"gray",54}, {"black",33}, {"gray",2}, {"black",1}, {"brown",1}, {"pink",37}},
  {{"gray",54}, {"black",32}, {"gray",2}, {"black",2}, {"gray",1}, {"lightGray",1}, {"pink",36}},
  {{"gray",53}, {"black",32}, {"gray",2}, {"black",4}, {"lightGray",1}, {"pink",1}, {"lightGray",7}, {"pink",7}, {"lightGray",1}, {"pink",7}, {"lightGray",13}},
  {{"gray",52}, {"black",31}, {"gray",2}, {"black",6}, {"gray",1}, {"pink",1}, {"lightGray",35}},
  {{"gray",52}, {"black",39}, {"gray",1}, {"pink",1}, {"lightGray",35}},
  {{"gray",51}, {"black",38}, {"gray",1}, {"black",1}, {"gray",1}, {"pink",1}, {"lightGray",35}},
  {{"gray",51}, {"black",33}, {"gray",1}, {"black",6}, {"gray",1}, {"lightGray",36}},
  {{"gray",51}, {"black",40}, {"brown",1}, {"lightGray",36}},
  {{"gray",51}, {"black",40}, {"lightGray",37}},
  {{"gray",50}, {"black",41}, {"lightGray",37}},
  {{"gray",50}, {"black",40}, {"gray",1}, {"lightGray",37}},
  {{"gray",49}, {"black",41}, {"gray",1}, {"lightGray",37}},
  {{"gray",48}, {"black",42}, {"lightGray",38}},
  {{"gray",32}, {"black",9}, {"gray",6}, {"black",43}, {"lightGray",38}},
  {{"gray",15}, {"black",3}, {"gray",2}, {"black",3}, {"gray",3}, {"black",16}, {"gray",4}, {"black",43}, {"gray",1}, {"lightGray",38}},
  {{"gray",13}, {"black",31}, {"gray",1}, {"black",44}, {"lightGray",39}},
  {{"gray",5}, {"black",1}, {"gray",2}, {"black",35}, {"gray",2}, {"black",43}, {"gray",1}, {"lightGray",39}},
  {{"gray",2}, {"black",40}, {"gray",1}, {"black",45}, {"lightGray",37}, {"brown",3}},
  {{"black",87}, {"gray",1}, {"lightGray",40}},
  {{"black",38}, {"gray",1}, {"black",48}, {"brown",1}, {"lightGray",40}},
  {{"gray",38}, {"black",49}, {"lightGray",41}},
  {{"gray",37}, {"black",50}, {"lightGray",41}},
  {{"gray",34}, {"black",53}, {"lightGray",26}, {"brown",1}, {"lightGray",12}, {"brown",1}, {"lightGray",1}},
  {{"gray",2}, {"black",1}, {"gray",3}, {"black",2}, {"gray",2}, {"black",1}, {"gray",3}, {"black",3}, {"gray",1}, {"black",1}, {"gray",11}, {"black",56}, {"brown",1}, {"lightGray",28}, {"brown",1}, {"lightGray",12}},
  {{"gray",5}, {"black",1}, {"gray",24}, {"black",56}, {"gray",3}, {"brown",1}, {"lightGray",27}, {"brown",1}, {"lightGray",10}},
  {{"gray",30}, {"black",61}, {"gray",2}, {"brown",1}, {"lightGray",23}, {"brown",4}, {"lightGray",2}, {"brown",5}},
  {{"gray",29}, {"black",66}, {"gray",1}, {"lightGray",23}, {"brown",3}, {"lightGray",3}, {"brown",3}},
  {{"gray",29}, {"black",68}, {"lightGray",20}, {"brown",2}, {"lightGray",2}, {"brown",3}, {"lightGray",2}, {"brown",2}},
  {{"gray",27}, {"black",70}, {"brown",1}, {"lightGray",1}, {"brown",11}, {"lightGray",4}, {"brown",1}, {"lightGray",8}, {"brown",5}},
  {{"gray",23}, {"black",2}, {"gray",1}, {"black",70}, {"gray",1}, {"brown",20}, {"lightGray",2}, {"brown",4}, {"lightGray",1}, {"brown",4}},
  {{"gray",25}, {"black",70}, {"gray",1}, {"brown",32}},
}

for y, row in ipairs(pixels) do
  local x = 1
  for _, seg in ipairs(row) do
    local col, count = seg[1], seg[2]
    mon.setCursorPos(x, y)
    mon.setBackgroundColor(colorMap[col])
    mon.write(string.rep(" ", count))
    x = x + count
  end
end